name: bsm-pymc3
channels:
- defaults
dependencies:
  - jupyter
  - mkl-service
  - pip
  - pip:
     - "git+git://github.com/arviz-devs/arviz.git@master"
     - "git+git://github.com/pymc-devs/pymc3.git@main"
