repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    -   id: check-toml
    -   id: check-yaml
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.5.5
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
      exclude: ^BCM/CaseStudies/MemoryRetention\.ipynb$
    - id: nbqa-isort
      additional_dependencies: [isort==5.6.4]
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.7.4]
