name: stat-rethink2-pymc
channels:
- conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - seaborn
  - mkl-service
  - watermark
  - pymc3
  - arviz
  - theano-pymc
  - mkl
  - mkl-service
  - pip
  - pip:
    - daft
    - causalgraphicalmodels
     - watermark
     - "git+git://github.com/arviz-devs/arviz.git@main"
     - "git+git://github.com/pymc-devs/pymc.git@main"
     - causalgraphicalmodels
     - daft
