name: stat-rethink2-pymc3
channels:
- defaults
dependencies:
  - jupyter
  - mkl-service
  - pip
  - pip:
     - watermark
     - "git+git://github.com/arviz-devs/arviz.git@main"
     - "git+git://github.com/pymc-devs/pymc3.git@master"
     - causalgraphicalmodels
     - daft
