name: stat-rethink2-pymc_v4
channels:
- conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - seaborn
  - mkl-service
  - watermark
  - pymc==4.0.0
  - arviz==0.12.1
  - aeppl==0.0.31
  - aesara==2.6.6
  - theano-pymc==1.1.2
  - tqdm
  - mkl
  - mkl-service
  - pip
  - pip:
    - daft
    - causalgraphicalmodels
     - watermark
     - "git+git://github.com/arviz-devs/arviz.git@main"
     - "git+git://github.com/pymc-devs/pymc.git@main"
     - causalgraphicalmodels
     - daft
